#!/usr/bin/env bash
# Script that configures Nginx for URL redirection

# Install Nginx if it's not already installed
if ! [ -x "$(command -v nginx)" ]; then
  sudo apt update
  sudo apt install nginx -y
fi

# Create a Nginx configuration file for the redirection
echo 'server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.nginx-debian.html;
    }
}' | sudo tee /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration for syntax errors
sudo nginx -t

# Reload Nginx to apply the changes
sudo systemctl reload nginx
